# encoding: UTF-8

FROM alpine:<%= ENV.fetch('TAG') %>
MAINTAINER Stefano Harding <riddopic@gmail.com>
COPY files/apk-install /usr/sbin/apk-install
RUN apk update && apk upgrade && apk-install bash tzdata